spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/pinnacle_developers?createDatabaseIfNotExist=true
spring.datasource.username=D3_92878_Vishal
spring.datasource.password=manager
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
